=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/test-case.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:runner="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner">
  <xs:element name="test-case">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        
      
		
			  <xs:element name="open">
			    <xs:complexType>
			      <xs:attribute name="href" use="required" type="xs:anyURI"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-title">
			    <xs:complexType>
			      <xs:attribute name="title" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-not-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-valid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-invalid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readonly">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readwrite">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-required">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-optional">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-selection-options">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="options" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="select-option">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="option" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="deselect-by-value">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-inner-html">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-inner-html-contains">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			      <xs:attribute name="trim" type="xs:boolean" use="optional" default="false"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value-contains">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value-in-range">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="start" use="required" type="xs:decimal"/>
			      <xs:attribute name="end" use="required" type="xs:decimal"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-exception">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="xforms-binding-exception"/>
			            <xs:enumeration value="xforms-compute-exception"/>
			            <xs:enumeration value="xforms-version-exception"/>
			            <xs:enumeration value="xforms-link-exception"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-message">
			    <xs:complexType>
			      <xs:attribute name="message" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-message-or-exception">
			    <xs:complexType>
			      <xs:attribute name="message" use="required"/>
			      <xs:attribute name="exception" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-messages">
			    <xs:complexType>
			      <xs:sequence>
			      	<xs:element name="message" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
			      </xs:sequence>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-no-messages"/>
			  <xs:element name="type-input">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
                  <xs:attribute name="incremental" use="optional" default="false"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="type-secret">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="type-textarea">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="click">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="wait-for-page-to-load" type="xs:string"/>
			  <xs:element name="assert-text-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-text-not-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="fail">
			    <xs:complexType>
			      <xs:attribute name="msg" use="required"/>
			    </xs:complexType>
			  </xs:element>
			</xs:choice>
	    </xs:complexType>
	</xs:element>
</xs:schema>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/Chapt04/4.6/4.6.3/4.6.3.c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
    <open href="Chapt04/4.6/4.6.3/4.6.3.c.xhtml"/>
    <assert-title title="4.6.3.c event sequencing for select/select1 controls with incremental=&#34;false&#34; (focus changes)"/>
    <deselect-by-value locator="xf-select-1" value="acu"/>
    <select-option locator="xf-select-1" option="Honda"/>
    <assert-control-value locator="C64" value="xforms-deselect (select)"/>
    <assert-control-value locator="C67" value="xforms-select (select)"/>

    <select-option locator="xf-select1-1" option="Honda"/>
    <assert-control-value locator="C70" value="xforms-recalculate"/>
    <assert-control-value locator="C73" value="xforms-revalidate"/>
    <assert-control-value locator="C76" value="xforms-refresh"/>


</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/unstable/Chapt10/10.4/10.4.e.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../test-case.xsd">
   <open href="Chapt10/10.4/10.4.e.xhtml"/>
   <assert-title title="10.4.e delete element rules"/>
   <assert-control-value locator="xf-input-1·1" value="3.00"/>
   <assert-control-value locator="xf-input-2·1" value="a"/>
   <assert-control-value locator="xf-input-1·2" value="32.25"/>
   <assert-control-value locator="xf-input-2·2" value="b"/>
   <assert-control-value locator="xf-input-1·3" value="132.99"/>
   <assert-control-value locator="xf-input-2·3" value="c"/>
   <assert-control-value locator="xf-input-1·4" value="1320.99"/>
   <assert-control-value locator="xf-input-2·4" value="d"/>
   <assert-control-value locator="xf-input-1·5" value="13200.99"/>
   <assert-control-value locator="xf-input-2·5" value="e"/>
   <assert-control-value locator="xf-input-1·6" value="132000.99"/>
   <assert-control-value locator="xf-input-2·6" value="f"/>
   
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-value locator="xf-input-1·1" value="32.25"/>
   <assert-control-value locator="xf-input-2·1" value="b"/>
   <assert-control-value locator="xf-input-1·2" value="132.99"/>
   <assert-control-value locator="xf-input-2·2" value="c"/>
   <assert-control-value locator="xf-input-1·3" value="1320.99"/>
   <assert-control-value locator="xf-input-2·3" value="d"/>
   <assert-control-value locator="xf-input-1·4" value="13200.99"/>
   <assert-control-value locator="xf-input-2·4" value="e"/>
   <assert-control-value locator="xf-input-1·5" value="132000.99"/>
   <assert-control-value locator="xf-input-2·5" value="f"/>
   <assert-control-not-present locator="xf-input-1·6" type="input"/>
   <assert-control-not-present locator="xf-input-2·6" type="input"/>
   <assert-control-value locator="xf-output-1" value="1"/>
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-value locator="xf-input-1·1" value="132.99"/>
   <assert-control-value locator="xf-input-2·1" value="c"/>
   <assert-control-value locator="xf-input-1·2" value="1320.99"/>
   <assert-control-value locator="xf-input-2·2" value="d"/>
   <assert-control-value locator="xf-input-1·3" value="13200.99"/>
   <assert-control-value locator="xf-input-2·3" value="e"/>
   <assert-control-value locator="xf-input-1·4" value="132000.99"/>
   <assert-control-value locator="xf-input-2·4" value="f"/>
   <assert-control-not-present locator="xf-input-1·5" type="input"/>
   <assert-control-not-present locator="xf-input-2·5" type="input"/>
   <assert-control-value locator="xf-output-1" value="1"/>
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-value locator="xf-input-1·1" value="1320.99"/>
   <assert-control-value locator="xf-input-2·1" value="d"/>
   <assert-control-value locator="xf-input-1·2" value="13200.99"/>
   <assert-control-value locator="xf-input-2·2" value="e"/>
   <assert-control-value locator="xf-input-1·3" value="132000.99"/>
   <assert-control-value locator="xf-input-2·3" value="f"/>
   <assert-control-not-present locator="xf-input-1·4" type="input"/>
   <assert-control-not-present locator="xf-input-2·4" type="input"/>
   <assert-control-value locator="xf-output-1" value="1"/>
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-value locator="xf-input-1·1" value="13200.99"/>
   <assert-control-value locator="xf-input-2·1" value="e"/>
   <assert-control-value locator="xf-input-1·2" value="132000.99"/>
   <assert-control-value locator="xf-input-2·2" value="f"/>
   <assert-control-not-present locator="xf-input-1·3" type="input"/>
   <assert-control-not-present locator="xf-input-2·3" type="input"/>
   <assert-control-value locator="xf-output-1" value="1"/>
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-value locator="xf-input-1·1" value="132000.99"/>
   <assert-control-value locator="xf-input-2·1" value="f"/>
   <assert-control-not-present locator="xf-input-1·2" type="input"/>
   <assert-control-not-present locator="xf-input-2·2" type="input"/>
   <assert-control-value locator="xf-output-1" value="1"/>
   
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-delete"/>
   <assert-control-not-present locator="xf-input-1·1" type="input"/>
   <assert-control-not-present locator="xf-input-2·1" type="input"/>
   <assert-control-value locator="xf-output-1" value="0"/>
   
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/unstable/Chapt10/10.3/10.3.f.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../test-case.xsd">
   <open href="Chapt10/10.3/10.3.f.xhtml"/>
   <assert-title title="10.3.f insert action in repeat bound to collection"/>
   <click locator="xf-trigger-1"/>
   <assert-message message="xforms-insert"/>
   <assert-control-value locator="xf-input-1·1" value="0.00"/>
   <assert-control-value locator="xf-input-2·1" value=""/>
   <assert-control-value locator="xf-input-1·2" value="3.00"/>
   <assert-control-value locator="xf-input-2·2" value="a"/>
   <assert-control-value locator="xf-input-1·3" value="32.25"/>
   <assert-control-value locator="xf-input-2·3" value="b"/>
   <assert-control-value locator="xf-input-1·4" value="132.99"/>
   <assert-control-value locator="xf-input-2·4" value="c"/>
   <assert-control-value locator="xf-input-3" value="1"/>
   
   <open href="Chapt10/10.3/10.3.f.xhtml"/>
   <assert-title title="10.3.f insert action in repeat bound to collection"/>
   <click locator="xf-trigger-2"/>
   <assert-message message="xforms-insert"/>
   <assert-control-value locator="xf-input-1·1" value="3.00"/>
   <assert-control-value locator="xf-input-2·1" value="a"/>
   <assert-control-value locator="xf-input-1·2" value="0.00"/>
   <assert-control-value locator="xf-input-2·2" value=""/>
   <assert-control-value locator="xf-input-1·3" value="32.25"/>
   <assert-control-value locator="xf-input-2·3" value="b"/>
   <assert-control-value locator="xf-input-1·4" value="132.99"/>
   <assert-control-value locator="xf-input-2·4" value="c"/>
   <assert-control-value locator="xf-input-3" value="2"/>
   
   <open href="Chapt10/10.3/10.3.f.xhtml"/>
   <assert-title title="10.3.f insert action in repeat bound to collection"/>
   <click locator="xf-trigger-3"/>
   <assert-message message="xforms-insert"/>
   <assert-control-value locator="xf-input-1·1" value="3.00"/>
   <assert-control-value locator="xf-input-2·1" value="a"/>
   <assert-control-value locator="xf-input-1·2" value="32.25"/>
   <assert-control-value locator="xf-input-2·2" value="b"/>
   <assert-control-value locator="xf-input-1·3" value="132.99"/>
   <assert-control-value locator="xf-input-2·3" value="c"/>
   <assert-control-value locator="xf-input-1·4" value="0.00"/>
   <assert-control-value locator="xf-input-2·4" value=""/>
   <assert-control-value locator="xf-input-3" value="4"/>
   
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/Chapt09/9.1/9.1.1/9.1.1.b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt09/9.1/9.1.1/9.1.1.b.xhtml"/>
   <assert-title title="9.1.1.b label element in a group element"/>
   <assert-text-present text="Shipping Address"/>
   <assert-control-present locator="xf-input-1" type="input"/>
   <assert-control-present locator="xf-input-2" type="input"/>
   <assert-text-present text="Shipping Date"/>
   <assert-control-present locator="xf-input-3" type="input"/>
   <assert-control-present locator="xf-input-4" type="input"/>
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/unstable/Chapt04/4.6/4.6.3/4.6.3.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt04/4.6/4.6.3/4.6.3.a.xhtml"/>
   <assert-title title="4.6.3.a event sequencing for select/select1 controls with incremental=&#34;true&#34;"/>
   <select-option locator="xf-select-1" option="Honda"/>
   <assert-control-value locator="C65" value="xforms-select (select)"/>
   <assert-control-value locator="C68" value="xforms-recalculate"/>
   <assert-control-value locator="C71" value="xforms-revalidate"/>
   <assert-control-value locator="C74" value="xforms-refresh"/>
   <assert-control-value locator="C77" value="xforms-value-changed (select)"/>

    <deselect-by-value locator="xf-select-1" value="hon"/>
   <assert-control-value locator="C80" value="xforms-deselect (select)"/>
   <assert-control-value locator="C83" value="xforms-recalculate"/>
   <assert-control-value locator="C86" value="xforms-revalidate"/>
   <assert-control-value locator="C89" value="xforms-refresh"/>
   <assert-control-value locator="C92" value="xforms-value-changed (select)"/>

    <open href="Chapt04/4.6/4.6.3/4.6.3.a.xhtml"/>
    <assert-alert message="This page is asking you to confirm that you want to leave - data you have entered may not be saved."/>
    <assert-title title="4.6.3.a event sequencing for select/select1 controls with incremental=&#34;true&#34;"/>
    <select-option locator="xf-select1-1" option="Honda"/>
    <assert-control-value locator="C65" value="xforms-select (select1)"/>
    <assert-control-value locator="C68" value="xforms-recalculate"/>
    <assert-control-value locator="C71" value="xforms-revalidate"/>
    <assert-control-value locator="C74" value="xforms-refresh"/>
    <assert-control-value locator="C77" value="xforms-value-changed (select1)"/>

    <select-option locator="xf-select1-1" option=""/>
    <assert-control-value locator="C80" value="xforms-deselect (select1)"/>
    <assert-control-value locator="C83" value="xforms-recalculate"/>
    <assert-control-value locator="C86" value="xforms-revalidate"/>
    <assert-control-value locator="C89" value="xforms-refresh"/>
    <assert-control-value locator="C92" value="xforms-value-changed (select1)"/>
</test-case>
