=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/test-case.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:runner="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner">
  <xs:element name="test-case">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        
      
		
			  <xs:element name="open">
			    <xs:complexType>
			      <xs:attribute name="href" use="required" type="xs:anyURI"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-title">
			    <xs:complexType>
			      <xs:attribute name="title" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-not-present">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="input"/>
			            <xs:enumeration value="secret"/>
			            <xs:enumeration value="textarea"/>
			            <xs:enumeration value="output"/>
			            <xs:enumeration value="upload"/>
			            <xs:enumeration value="range"/>
			            <xs:enumeration value="trigger"/>
			            <xs:enumeration value="submit"/>
			            <xs:enumeration value="select"/>
			            <xs:enumeration value="select1"/>
			            <xs:enumeration value="group"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-valid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-invalid">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readonly">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-readwrite">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-required">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-optional">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-selection-options">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="options" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="select-option">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="option" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="deselect-by-value">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-inner-html">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-inner-html-contains">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			      <xs:attribute name="trim" type="xs:boolean" use="optional" default="false"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value-contains">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-control-value-in-range">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="start" use="required" type="xs:decimal"/>
			      <xs:attribute name="end" use="required" type="xs:decimal"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-exception">
			    <xs:complexType>
			      <xs:attribute name="type" use="required">
			        <xs:simpleType>
			          <xs:restriction base="xs:token">
			            <xs:enumeration value="xforms-binding-exception"/>
			            <xs:enumeration value="xforms-compute-exception"/>
			            <xs:enumeration value="xforms-version-exception"/>
			            <xs:enumeration value="xforms-link-exception"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-message">
			    <xs:complexType>
			      <xs:attribute name="message" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-message-or-exception">
			    <xs:complexType>
			      <xs:attribute name="message" use="required"/>
			      <xs:attribute name="exception" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-messages">
			    <xs:complexType>
			      <xs:sequence>
			      	<xs:element name="message" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
			      </xs:sequence>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-no-messages"/>
			  <xs:element name="type-input">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
                  <xs:attribute name="incremental" use="optional" default="false"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="type-secret">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="type-textarea">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			      <xs:attribute name="value" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="click">
			    <xs:complexType>
			      <xs:attribute name="locator" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="wait-for-page-to-load" type="xs:string"/>
			  <xs:element name="assert-text-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="assert-text-not-present">
			    <xs:complexType>
			      <xs:attribute name="text" use="required"/>
			    </xs:complexType>
			  </xs:element>
			  <xs:element name="fail">
			    <xs:complexType>
			      <xs:attribute name="msg" use="required"/>
			    </xs:complexType>
			  </xs:element>
			</xs:choice>
	    </xs:complexType>
	</xs:element>
</xs:schema>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/Chapt02/2.4.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../test-case.xsd">
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<assert-selection-options locator="xf-select1-1" options="Cash,Credit"/>
	<assert-control-present locator="xf-input-1" type="input"/>
	<assert-control-present locator="xf-input-2" type="input"/>
	<select-option locator="xf-select1-1" option="Cash"/>
	<assert-control-not-present locator="xf-input-1" type="input"/>
	<assert-control-not-present locator="xf-input-2" type="input"/>
	<click locator="xf-submit-1"/>
	<wait-for-page-to-load/>
	<assert-title title="Results from echo.sh"/>
	<assert-text-present text="method=&#34;cash&#34;"/>
	<assert-text-not-present text="&lt;number"/>
	<assert-text-not-present text="&lt;expiry"/>
	<assert-text-not-present text="helpful"/>
	
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<type-input locator="xf-input-1" value="4012888888881881"/>
	<type-input locator="xf-input-2" value="2001"/>
	<click locator="xf-submit-1"/>
	<assert-control-invalid locator="xf-input-2"/>
	<type-input locator="xf-input-2" value="2001-08"/>
	<click locator="xf-submit-1"/>
	<wait-for-page-to-load/>
	<assert-title title="Results from echo.sh"/>
	<assert-text-present text="method=&#34;cc&#34;"/>
	<assert-text-present text="&lt;number&gt;4012888888881881&lt;/number&gt;"/>
	<assert-text-present text="&lt;expiry&gt;2001-08&lt;/expiry&gt;"/> 
	<assert-text-not-present text="helpful"/>
	
	<open href="Chapt02/2.4.a.xhtml"/>
	<assert-title title="2.4.a Example: Multiple Forms"/>
	<assert-selection-options locator="xf-select1-2" options="Not at all helpful (0),Barely helpful (1),Somewhat helpful (2),Very helpful (3)"/>
	<click locator="xf-submit-2"/>
	<wait-for-page-to-load/>
	<assert-title title="Results from echo.sh"/>
	<assert-text-present text="&lt;helpful&gt;3&lt;/helpful&gt;"/>
	<assert-text-not-present text="method"/>
	
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/Chapt05/5.2/5.2.7/5.2.7.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt05/5.2/5.2.7/5.2.7.a.xhtml"/>
   <assert-title title="5.2.7.a card-number datatype"/>
   <click locator="xf-trigger-1"/>
   <assert-message message="You entered a valid card-number"/>
   <click locator="xf-trigger-2"/>
   <assert-message message="You entered a valid card-number"/>
   <click locator="xf-trigger-3"/>
   <assert-message message="You entered an invalid card-number"/>
   <click locator="xf-trigger-4"/>
   <assert-message message="You entered an invalid card-number"/>
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/unstable/Chapt05/5.1/5.1.b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../test-case.xsd">
   <open href="Chapt05/5.1/5.1.b.xhtml"/>
   <assert-title title="5.1.b built-in derived types"/>
   <click locator="xf-trigger-1"/>
   <assert-control-value-contains locator="xf-output-1·1" value="xforms-valid (normalizedString)"/>
   <assert-control-value-contains locator="xf-output-1·2" value="xforms-valid (token)"/>
   <assert-control-value-contains locator="xf-output-1·3" value="xforms-valid (language)"/>
   <assert-control-value-contains locator="xf-output-1·4" value="xforms-valid (Name)"/>
   <assert-control-value-contains locator="xf-output-1·5" value="xforms-valid (NCName)"/>
   <assert-control-value-contains locator="xf-output-1·6" value="xforms-valid (ID)"/>
   <assert-control-value-contains locator="xf-output-1·7" value="xforms-valid (IDREF)"/>
   <assert-control-value-contains locator="xf-output-1·8" value="xforms-valid (IDREFS)"/>
   <assert-control-value-contains locator="xf-output-1·9" value="xforms-valid (NMTOKEN)"/>
   <assert-control-value-contains locator="xf-output-1·10" value="xforms-valid (NMTOKENS)"/>
   <assert-control-value-contains locator="xf-output-1·11" value="xforms-valid (integer)"/>
   <assert-control-value-contains locator="xf-output-1·12" value="xforms-valid (nonPositiveInteger)"/>
   <assert-control-value-contains locator="xf-output-1·13" value="xforms-valid (negativeInteger)"/>
   <assert-control-value-contains locator="xf-output-1·14" value="xforms-valid (long)"/>
   <assert-control-value-contains locator="xf-output-1·15" value="xforms-valid (int)"/>
   <assert-control-value-contains locator="xf-output-1·16" value="xforms-valid (short)"/>
   <assert-control-value-contains locator="xf-output-1·17" value="xforms-valid (byte)"/>
   <assert-control-value-contains locator="xf-output-1·18" value="xforms-valid (nonNegativeInteger)"/>
   <assert-control-value-contains locator="xf-output-1·19" value="xforms-valid (unsignedLong)"/>
   <assert-control-value-contains locator="xf-output-1·20" value="xforms-valid (unsignedInt)"/>
   <assert-control-value-contains locator="xf-output-1·21" value="xforms-valid (unsignedShort)"/>
   <assert-control-value-contains locator="xf-output-1·22" value="xforms-valid (unsignedByte)"/>
   <assert-control-value-contains locator="xf-output-1·23" value="xforms-valid (positiveInteger)"/>
   <click locator="xf-trigger-2"/>
   <assert-control-value-contains locator="xf-output-1·1" value="XFORMS-INVALID (normalizedString)"/>
   <assert-control-value-contains locator="xf-output-1·2" value="XFORMS-INVALID (token)"/>
   <assert-control-value-contains locator="xf-output-1·3" value="XFORMS-INVALID (language)"/>
   <assert-control-value-contains locator="xf-output-1·4" value="XFORMS-INVALID (Name)"/>
   <assert-control-value-contains locator="xf-output-1·5" value="XFORMS-INVALID (NCName)"/>
   <assert-control-value-contains locator="xf-output-1·6" value="XFORMS-INVALID (ID)"/>
   <assert-control-value-contains locator="xf-output-1·7" value="XFORMS-INVALID (IDREF)"/>
   <assert-control-value-contains locator="xf-output-1·8" value="XFORMS-INVALID (IDREFS)"/>
   <assert-control-value-contains locator="xf-output-1·9" value="xforms-valid (NMTOKEN)"/>
   <assert-control-value-contains locator="xf-output-1·10" value="xforms-valid (NMTOKENS)"/>
   <assert-control-value-contains locator="xf-output-1·11" value="XFORMS-INVALID (integer)"/>
   <assert-control-value-contains locator="xf-output-1·12" value="XFORMS-INVALID (nonPositiveInteger)"/>
   <assert-control-value-contains locator="xf-output-1·13" value="XFORMS-INVALID (negativeInteger)"/>
   <assert-control-value-contains locator="xf-output-1·14" value="XFORMS-INVALID (long)"/>
   <assert-control-value-contains locator="xf-output-1·15" value="XFORMS-INVALID (int)"/>
   <assert-control-value-contains locator="xf-output-1·16" value="XFORMS-INVALID (short)"/>
   <assert-control-value-contains locator="xf-output-1·17" value="XFORMS-INVALID (byte)"/>
   <assert-control-value-contains locator="xf-output-1·18" value="XFORMS-INVALID (nonNegativeInteger)"/>
   <assert-control-value-contains locator="xf-output-1·19" value="XFORMS-INVALID (unsignedLong)"/>
   <assert-control-value-contains locator="xf-output-1·20" value="XFORMS-INVALID (unsignedInt)"/>
   <assert-control-value-contains locator="xf-output-1·21" value="XFORMS-INVALID (unsignedShort)"/>
   <assert-control-value-contains locator="xf-output-1·22" value="XFORMS-INVALID (unsignedByte)"/>
   <assert-control-value-contains locator="xf-output-1·23" value="XFORMS-INVALID (positiveInteger)"/>
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/unstable/Chapt05/5.1/5.1.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../test-case.xsd">
   <open href="Chapt05/5.1/5.1.a.xhtml"/>
   <assert-title title="5.1.a built-in primitive types"/>
   <click locator="xf-trigger-1"/>
   <assert-control-value-contains locator="xf-output-1·1" value="xforms-valid (dateTime)"/>
   <assert-control-value-contains locator="xf-output-1·2" value="xforms-valid (time)"/>
   <assert-control-value-contains locator="xf-output-1·3" value="xforms-valid (date)"/>
   <assert-control-value-contains locator="xf-output-1·4" value="xforms-valid (gYearMonth)"/>
   <assert-control-value-contains locator="xf-output-1·5" value="xforms-valid (gYear)"/>
   <assert-control-value-contains locator="xf-output-1·6" value="xforms-valid (gMonthDay)"/>
   <assert-control-value-contains locator="xf-output-1·7" value="xforms-valid (gDay)"/>
   <assert-control-value-contains locator="xf-output-1·8" value="xforms-valid (gMonth)"/>
   <assert-control-value-contains locator="xf-output-1·9" value="xforms-valid (string)"/>
   <assert-control-value-contains locator="xf-output-1·10" value="xforms-valid (boolean)"/>
   <assert-control-value-contains locator="xf-output-1·11" value="xforms-valid (base64Binary)"/>
   <assert-control-value-contains locator="xf-output-1·12" value="xforms-valid (hexBinary)"/>
   <assert-control-value-contains locator="xf-output-1·13" value="xforms-valid (float)"/>
   <assert-control-value-contains locator="xf-output-1·14" value="xforms-valid (decimal)"/>
   <assert-control-value-contains locator="xf-output-1·15" value="xforms-valid (double)"/>
   <assert-control-value-contains locator="xf-output-1·16" value="xforms-valid (anyURI)"/>
   <assert-control-value-contains locator="xf-output-1·17" value="xforms-valid (QName)"/>
   
   <click locator="xf-trigger-2"/>
   <assert-control-value-contains locator="xf-output-1·1" value="XFORMS-INVALID (dateTime)"/>
   <assert-control-value-contains locator="xf-output-1·2" value="XFORMS-INVALID (time)"/>
   <assert-control-value-contains locator="xf-output-1·3" value="XFORMS-INVALID (date)"/>
   <assert-control-value-contains locator="xf-output-1·4" value="XFORMS-INVALID (gYearMonth)"/>
   <assert-control-value-contains locator="xf-output-1·5" value="XFORMS-INVALID (gYear)"/>
   <assert-control-value-contains locator="xf-output-1·6" value="XFORMS-INVALID (gMonthDay)"/>
   <assert-control-value-contains locator="xf-output-1·7" value="XFORMS-INVALID (gDay)"/>
   <assert-control-value-contains locator="xf-output-1·8" value="XFORMS-INVALID (gMonth)"/>
   <assert-control-value-contains locator="xf-output-1·9" value="xforms-valid (string)"/>
   <assert-control-value-contains locator="xf-output-1·10" value="XFORMS-INVALID (boolean)"/>
   <assert-control-value-contains locator="xf-output-1·11" value="XFORMS-INVALID (base64Binary)"/>
   <assert-control-value-contains locator="xf-output-1·12" value="XFORMS-INVALID (hexBinary)"/>
   <assert-control-value-contains locator="xf-output-1·13" value="XFORMS-INVALID (float)"/>
   <assert-control-value-contains locator="xf-output-1·14" value="XFORMS-INVALID (decimal)"/>
   <assert-control-value-contains locator="xf-output-1·15" value="XFORMS-INVALID (double)"/>
   <assert-control-value-contains locator="xf-output-1·16" value="XFORMS-INVALID (anyURI)"/>
   <assert-control-value-contains locator="xf-output-1·17" value="XFORMS-INVALID (QName)"/>
</test-case>

=== betterFORM/betterFORM-limegreen/web/src/test/resources/testsuite/xml/stable/Chapt04/4.6/4.6.3/4.6.3.b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2010, Nick Van den Bleeken
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT 
SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, 
STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<test-case xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner" xmlns:xf="http://www.w3.org/2002/xforms" xsi:schemaLocation="http://www.w3c.org/MarkUp/Forms/XForms/Test/Runner ../../../test-case.xsd">
   <open href="Chapt04/4.6/4.6.3/4.6.3.b.xhtml"/>
   <assert-title title="4.6.3.b event sequencing for select/select1 controls with incremental=&#34;false&#34;"/>
    <deselect-by-value locator="xf-select-1" value="acu"/>
   <select-option locator="xf-select-1" option="Honda"/>

   <assert-control-value locator="C64" value="xforms-deselect (select)"/>
   <assert-control-value locator="C67" value="xforms-select (select)"/>

   <open href="Chapt04/4.6/4.6.3/4.6.3.b.xhtml"/>
   <!--<assert-alert message="This page is asking you to confirm that you want to leave - data you have entered may not be saved."/>-->
   <assert-title title="4.6.3.b event sequencing for select/select1 controls with incremental=&#34;false&#34;"/>
   <select-option locator="xf-select1-1" option="Honda"/>
   <assert-control-value locator="C64" value="xforms-deselect (select1)"/>
   <assert-control-value locator="C67" value="xforms-select (select1)"/>

</test-case>
